### ISSUE TITLE
how to find the wider_resnet38.pth.tar

### ISSUE THREAD

**Issue by Rebecaa000** [haruishi43/GSCNN#1]
I wanna ask pretrained models are wider_resnet38.pth.tar or best_cityscapes_checkpoint.pth?
Does the wider_resnet38.pth.tar have to be trained on NVIDIA/semantic-segmentation? Is there a specific method of operation?

**Comment by Rebecaa000** [comment]
> I wanna ask pretrained models are wider_resnet38.pth.tar or best_cityscapes_checkpoint.pth? Does the wider_resnet38.pth.tar have to be trained on NVIDIA/semantic-segmentation? Is there a specific method of operation?

I find it in NVIDIA/semantic-segmentation(https://drive.google.com/drive/folders/1fs-uLzXvmsISbS635eRZCc5uzQdBIZ_U)
thanks

**Comment by haruishi43** [comment]
@Rebecaa000 `wider_resnet38.pth.tar` just needs to be in `/pretrained_models/`. The [initialization function](https://github.com/haruishi43/GSCNN/blob/f219bd3702a1ba648a10774e2bbee7e090a33a4b/sseg/network/wider_resnet.py#L456) will automatically load it. If you want to use `best_cityscapes_checkpoint.pth` you could change the path in the function (you might need fix some mappings for the keys).

> I find it in NVIDIA/semantic-segmentation(https://drive.google.com/drive/folders/1fs-uLzXvmsISbS635eRZCc5uzQdBIZ_U) thanks

Yeah, the google drive url moved, I might need to update it.
